# SentinelOS: read-only environment inspection. Installs and changes nothing.
#   powershell -ExecutionPolicy Bypass -File scripts\inspect_env.ps1
# Writes sentinel_env.txt (repo root) and docs\environment.md.
# Sanitized: the Windows username is replaced with <user>; no serial numbers or product keys are read.

$ErrorActionPreference = "Continue"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

function Sanitize([string]$s) {
    if ($env:USERNAME) { $s = $s -replace [regex]::Escape($env:USERNAME), '<user>' }
    if ($env:COMPUTERNAME) { $s = $s -replace [regex]::Escape($env:COMPUTERNAME), '<computer>' }
    return $s
}

function Try-Run($label, [scriptblock]$sb) {
    $body = try { (& $sb 2>&1 | Out-String -Width 200).Trim() } catch { "NOT AVAILABLE: $($_.Exception.Message)" }
    if (-not $body) { $body = "Not detected" }
    return [pscustomobject]@{ Label = $label; Body = (Sanitize $body) }
}

$sections = @(
    Try-Run "Laptop model" { Get-CimInstance Win32_ComputerSystem | Select-Object Manufacturer, Model, @{n='RAM_GB';e={[math]::Round($_.TotalPhysicalMemory/1GB,1)}} | Format-List }
    Try-Run "Processor" { Get-CimInstance Win32_Processor | Select-Object Name, Manufacturer, NumberOfCores, NumberOfLogicalProcessors | Format-List }
    Try-Run "Windows" { Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version, BuildNumber, OSArchitecture | Format-List; "PROCESSOR_ARCHITECTURE=$env:PROCESSOR_ARCHITECTURE" }
    Try-Run "Free storage (system drive)" { Get-PSDrive -Name ($env:SystemDrive.TrimEnd(':')) | Select-Object @{n='Free_GB';e={[math]::Round($_.Free/1GB,1)}}, @{n='Used_GB';e={[math]::Round($_.Used/1GB,1)}} | Format-List }
    Try-Run "NPU / compute accelerators" { Get-PnpDevice -PresentOnly | Where-Object { $_.FriendlyName -match 'NPU|Hexagon|Neural' -or $_.Class -match 'Neural|Compute' } | Select-Object FriendlyName, Class, Status | Format-Table -AutoSize }
    Try-Run "NPU driver" { Get-CimInstance Win32_PnPSignedDriver | Where-Object { $_.DeviceName -match 'NPU|Hexagon' } | Select-Object DeviceName, DriverVersion, DriverDate | Format-List }
    Try-Run "GPU" { Get-CimInstance Win32_VideoController | Select-Object Name, DriverVersion | Format-List }
    Try-Run "Node / npm" { node -v; npm -v }
    Try-Run "Installed Pythons (py launcher)" { py -0p }
    Try-Run "Default Python + architecture (ARM64 = native, AMD64 = emulated x64)" { python -c "import platform,sys; print(sys.version); print('machine =', platform.machine())" }
    Try-Run "ONNX Runtime + execution providers" { python -c "import onnxruntime as o; print(o.__version__); print(o.get_available_providers())" }
    Try-Run "Relevant pip packages" { python -m pip list 2>$null | Select-String -Pattern 'onnx|qai|qnn|torch|transformers|numpy' }
    Try-Run "Visual Studio / Build Tools" { & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -all -format text -property displayName }
    Try-Run "Git" { git --version }
)

$txt = foreach ($s in $sections) { "`n==== $($s.Label) ====`n$($s.Body)" }
$txt | Set-Content -Encoding UTF8 sentinel_env.txt

$md = @("# Environment", "", "Generated by ``scripts/inspect_env.ps1`` on $(Get-Date -Format s). Machine-written; re-run to update.", "Usernames and computer names are replaced with placeholders.", "")
foreach ($s in $sections) { $md += "## $($s.Label)"; $md += ""; $md += '```'; $md += $s.Body; $md += '```'; $md += "" }
New-Item -ItemType Directory -Force docs | Out-Null
$md | Set-Content -Encoding UTF8 docs\environment.md

$txt
Write-Host "`nSaved sentinel_env.txt and docs\environment.md"
